const CACHE_NAME ='pravoslavna-riznica-final-v72';
const OFFLINE_ASSETS = [
  './',
  './index.html',
  './psaltir.html',
  './molitvenik.html',
  './novi-zavet.html',
  './ohridski-prolog.html',
  './duhovne-pouke.html',
  './duhovne-poucne-price.html',
  './praznici.html',
  './post-i-trapave-sedmice.html',
  './vaskrsnji-kalendar.html',
 './pojas-presvete-bogorodice.jpg',
  './audio-psaltir-katizme.html',
  './psaltir1/001.mp3',
  './psaltir1/002.mp3',
  './psaltir1/003.mp3',
  './psaltir1/004.mp3',
  './psaltir1/005.mp3',
  './psaltir1/006.mp3',
  './psaltir1/007.mp3',
  './psaltir1/008.mp3',
  './psaltir1/009.mp3',
  './psaltir1/010.mp3',
  './psaltir1/011.mp3',
  './psaltir1/012.mp3',
  './psaltir1/013.mp3',
  './psaltir1/014.mp3',
  './psaltir1/015.mp3',
  './psaltir1/016.mp3',
  './psaltir1/017.mp3',
  './psaltir1/018.mp3',
  './psaltir1/019.mp3',
  './psaltir1/020.mp3',
  './psaltir1/021.mp3',
  './psaltir1/022.mp3',
  './psaltir1/023.mp3',
  './psaltir1/024.mp3',
  './psaltir1/025.mp3',
  './psaltir1/026.mp3',
  './psaltir1/027.mp3',
  './psaltir1/028.mp3',
  './psaltir1/029.mp3',
  './psaltir1/030.mp3',
  './psaltir1/031.mp3',
  './psaltir1/032.mp3',
  './psaltir1/033.mp3',
  './psaltir1/034.mp3',
  './psaltir1/035.mp3',
  './psaltir1/036.mp3',
  './psaltir1/037.mp3',
  './psaltir1/038.mp3',
  './psaltir1/039.mp3',
  './psaltir1/040.mp3',
  './psaltir1/041.mp3',
  './psaltir2/042.mp3',
  './psaltir2/043.mp3',
  './psaltir2/044.mp3',
  './psaltir2/045.mp3',
  './psaltir2/046.mp3',
  './psaltir2/047.mp3',
  './psaltir2/048.mp3',
  './psaltir2/049.mp3',
  './psaltir2/050.mp3',
  './psaltir2/051.mp3',
  './psaltir2/052.mp3',
  './psaltir2/053.mp3',
  './psaltir2/054.mp3',
  './psaltir2/055.mp3',
  './psaltir2/056.mp3',
  './psaltir2/057.mp3',
  './psaltir2/058.mp3',
  './psaltir2/059.mp3',
  './psaltir2/060.mp3',
  './psaltir2/061.mp3',
  './psaltir2/062.mp3',
  './psaltir2/063.mp3',
  './psaltir2/064.mp3',
  './psaltir2/065.mp3',
  './psaltir2/066.mp3',
  './psaltir2/067.mp3',
  './psaltir2/068.mp3',
  './psaltir2/069.mp3',
  './psaltir2/070.mp3',
  './psaltir2/071.mp3',
  './psaltir2/072.mp3',
  './psaltir3/073.mp3',
  './psaltir3/074.mp3',
  './psaltir3/075.mp3',
  './psaltir3/076.mp3',
  './psaltir3/077.mp3',
  './psaltir3/078.mp3',
  './psaltir3/079.mp3',
  './psaltir3/080.mp3',
  './psaltir3/081.mp3',
  './psaltir3/082.mp3',
  './psaltir3/083.mp3',
  './psaltir3/084.mp3',
  './psaltir3/085.mp3',
  './psaltir3/086.mp3',
  './psaltir3/087.mp3',
  './psaltir3/088.mp3',
  './psaltir3/089.mp3',
  './psaltir4/090.mp3',
  './psaltir4/091.mp3',
  './psaltir4/092.mp3',
  './psaltir4/093.mp3',
  './psaltir4/094.mp3',
  './psaltir4/095.mp3',
  './psaltir4/096.mp3',
  './psaltir4/097.mp3',
  './psaltir4/098.mp3',
  './psaltir4/099.mp3',
  './psaltir4/100.mp3',
  './psaltir4/101.mp3',
  './psaltir4/102.mp3',
  './psaltir4/103.mp3',
  './psaltir4/104.mp3',
  './psaltir4/105.mp3',
  './psaltir4/106.mp3',
  './psaltir5/107.mp3',
  './psaltir5/108.mp3',
  './psaltir5/109.mp3',
  './psaltir5/110.mp3',
  './psaltir5/111.mp3',
  './psaltir5/112.mp3',
  './psaltir5/113.mp3',
  './psaltir5/114.mp3',
  './psaltir5/115.mp3',
  './psaltir5/116.mp3',
  './psaltir5/117.mp3',
  './psaltir5/118.mp3',
  './psaltir5/119.mp3',
  './psaltir5/120.mp3',
  './psaltir5/121.mp3',
  './psaltir5/122.mp3',
  './psaltir5/123.mp3',
  './psaltir5/124.mp3',
  './psaltir5/125.mp3',
  './psaltir5/126.mp3',
  './psaltir5/127.mp3',
  './psaltir5/128.mp3',
  './psaltir5/129.mp3',
  './psaltir5/130.mp3',
  './psaltir5/131.mp3',
  './psaltir5/132.mp3',
  './psaltir5/133.mp3',
  './psaltir5/134.mp3',
  './psaltir5/135.mp3',
  './psaltir5/136.mp3',
  './psaltir5/137.mp3',
  './psaltir5/138.mp3',
  './psaltir5/139.mp3',
  './psaltir5/140.mp3',
  './psaltir5/141.mp3',
  './psaltir5/142.mp3',
  './psaltir5/143.mp3',
  './psaltir5/144.mp3',
  './psaltir5/145.mp3',
  './psaltir5/146.mp3',
  './psaltir5/147.mp3',
  './psaltir5/148.mp3',
  './psaltir5/149.mp3',
  './psaltir5/150.mp3',

  './matej/01.mp3',
  './matej/02.mp3',
  './matej/03.mp3',
  './matej/04.mp3',
  './matej/05.mp3',
  './matej/06.mp3',
  './matej/07.mp3',
  './matej/08.mp3',
  './matej/09.mp3',
  './matej/10.mp3',
  './matej/11.mp3',
  './matej/12.mp3',
  './matej/13.mp3',
  './matej/14.mp3',
  './matej1/15.mp3',
  './matej1/16.mp3',
  './matej1/17.mp3',
  './matej1/18.mp3',
  './matej1/19.mp3',
  './matej1/20.mp3',
  './matej1/21.mp3',
  './matej1/22.mp3',
  './matej1/23.mp3',
  './matej1/24.mp3',
  './matej1/25.mp3',
  './matej1/26.mp3',
  './matej1/27.mp3',
  './matej1/28.mp3',
  './marko/01.mp3',
  './marko/02.mp3',
  './marko/03.mp3',
  './marko/04.mp3',
  './marko/05.mp3',
  './marko/06.mp3',
  './marko/07.mp3',
  './marko/08.mp3',
  './marko/09.mp3',
  './marko/10.mp3',
  './marko/11.mp3',
  './marko/12.mp3',
  './marko/13.mp3',
  './marko/14.mp3',
  './marko/15.mp3',
  './marko/16.mp3',
  './marko/17.mp3',
  './marko/18.mp3',
  './luka/01.mp3',
  './luka/02.mp3',
  './luka/03.mp3',
  './luka/04.mp3',
  './luka/05.mp3',
  './luka/06.mp3',
  './luka/07.mp3',
  './luka/08.mp3',
  './luka/09.mp3',
  './luka/10.mp3',
  './luka/11.mp3',
  './luka/12.mp3',
  './luka1/13.mp3',
  './luka1/14.mp3',
  './luka1/15.mp3',
  './luka1/16.mp3',
  './luka1/17.mp3',
  './luka1/18.mp3',
  './luka1/19.mp3',
  './luka1/20.mp3',
  './luka1/21.mp3',
  './luka1/22.mp3',
  './luka1/23.mp3',
  './luka1/24.mp3',
  './jovan/01.mp3',
  './jovan/02.mp3',
  './jovan/03.mp3',
  './jovan/04.mp3',
  './jovan/05.mp3',
  './jovan/06.mp3',
  './jovan/07.mp3',
  './jovan/08.mp3',
  './jovan/09.mp3',
  './jovan/10.mp3',
  './jovan/11.mp3',
  './jovan/12.mp3',
  './jovan/13.mp3',
  './jovan/14.mp3',
  './jovan/15.mp3',
  './jovan/16.mp3',
  './jovan/17.mp3',
  './jovan/18.mp3',
  './jovan/19.mp3',
  './jovan/20.mp3',
  './jovan/21.mp3',

  
  './akatist-presvetoj-bogorodici.html',
  './akatist-svetom-nektariju-eginskom.html',
  './akatist-svetoj-kseniji-petrogradskoj.html',

 
  './jednom-za-ceo-zivot.html',
  './sedam-znakova-novog-rodjenja.html',
  './boziji-promisao.html',
  './januar-2026.html',
  './februar-2026.html',
  './mart-2026.html',
  './april-2026.html',
  './maj-2026.html',
  './jun-2026.html',
  './jul-2026.html',
  './avgust-2026.html',
  './septembar-2026.html',
  './oktobar-2026.html',
  './novembar-2026.html',
  './decembar-2026.html',
  './prolog-januar.html',
  './prolog-februar.html',
  './prolog-mart.html',
  './prolog-april.html',
  './prolog-maj.html',
  './prolog-jun.html',
  './prolog-jul.html',
  './prolog-avgust.html',
  './prolog-septembar.html',
  './prolog-oktobar.html',
  './prolog-novembar.html',
  './prolog-decembar.html',
  './zitije-bozic.html',
  './zitije-arandjelovdan.html',
  './zitije-blagovesti.html',
  './zitije-bogojavljenje.html',
  './zitije-cveti.html',
  './zitije-djurdjevdan.html',
  './zitije-duhovski-ponedeljak.html',
  './zitije-duhovski-utorak.html',
  './zitije-ivanjdan.html',
  './zitije-jovankrstitelj.html',
  './zitije-kirilo-metodije.html',
  './zitije-konstantin-jelena.html',
  './zitije-vidovdan.html',
  './zitije-krstovdan.html',
  './zitije-mala-gospojina.html',
  './zitije-mitrovdan.html',
  './zitije-nikoljdan.html',
  './zitije-petar-cetinjski.html',
  './zitije-petrovdan.html',
  './zitije-preobrazenje.html',
  './zitije-prorok-ilija.html',
  './zitije-sabor.html',
  './zitije-silazak-duha-svetoga.html',
  './zitije-sretenje-gospodnje.html',
  './zitije-sv-sava.html',
  './zitije-sveta-petka.html',
  './zitije-sveta-tri-jerarha.html',
  './zitije-sveti-prvomucenik-stefan.html',
  './zitije-sveti-vasilije-veliki.html',
  './zitije-usekovanje.html',
  './zitije-uspenije.html',
  './zitije-vasilije-ostroski.html',
  './zitije-vaskrs.html',
  './zitije-vaskrsni-ponedeljak.html',
  './zitije-vaskrsni-utorak.html',
  './zitije-vavedenje.html',
  './zitije-vaznesenje.html',
  './zitije-veliki-petak.html',

   './ikone-danas/jun19-1.jpg',
  './ikone-danas/jun19-2.jpg',
  
  './screen1.png',
  './screen2.png',
  './screen3.png',
  './screen4.png',
  './screen5.png',
  './screen6.png',
  './screen7.png',
  './vidovdan.jpg',
  './veliki-petak.jpg',
  './vaznesenje.jpg',
  './vavedenje.jpg',
  './vaskrsni-utorak.jpg',
  './vaskrsni-ponedeljak.jpg',
  './vaskrs.jpg',
  './vasilije-ostroski.jpg',
  './uspenije.jpg',
  './usekovanje.jpg',
  './trojerucica.png',
  './tisina-snaga.png',
  './sveti-vasilije-veliki.jpg',
  './sveti-prvomucenik-stefan.jpg',
  './sveta-tri-jerarha.jpg',
  './sveta-petka.jpg',
  './sve-primi-mirno.png',
  './sv-sava.jpg',
  './stiker-bog.png',
  './svako-dobro.png',
  './sretenje-gospodnje.jpg',
  './snaga.png',
  './silazak-duha-svetoga.jpg',
  './serafimi.png',
  './sabor.jpg',
  './prorok-ilija.jpg',
  './pricest.png',
  './preobrazenje.jpg',
  './prastaj-i-ljubi.png',
  './pokajnik.png',
  './petrovdan.jpg',
  './petar-cetinjski.jpg',
  './papir.png',
  './papir.jpg',
  './oprostaj.png',
  './nikoljdan.jpg',
  './nikolaj.jpg',
  './mojstiker.png',
  './mitrovdan.jpg',
  './mala-gospojina.jpg',
  './ljubi-i-prastaj.png',
  './krstovdan.jpg',
  './krst.png',
 './krst-ornament-veliki.png',
  './konstantin-jelena.jpg',
  './kirilo-metodije.jpg',
  './justin.jpg',
  './jovankrstitelj.jpg',
  './ivanjdan.jpg',
  './isceliteljka.png',
  './ikona.png',
  './hram.png',
  './gospode-oprosti-i-osvetli-mi-put.png',
  './duhovski-utorak.jpg',
  './duhovski-ponedeljak.jpg',
  './djurdjevdan.jpg',
  './cveti.jpg',
  './bozija-volja.png',
  './bozic.jpg',
  './bogorodica.png',
  './bogorodica-pehar.png',
  './bogorodica-hrist.png',
  './bogojavljenje.jpg',
  './bog-cuti.png',
  './blagovesti.jpg',
  './arandjelovdan.jpg',
  './andjeo.png',
  './jovan-1.html', './jovan-2.html', './jovan-3.html', './jovan-4.html', './jovan-5.html',
  './jovan-6.html', './jovan-7.html', './jovan-8.html', './jovan-9.html', './jovan-10.html',
  './jovan-11.html', './jovan-12.html', './jovan-13.html', './jovan-14.html', './jovan-15.html',
  './jovan-16.html', './jovan-17.html', './jovan-18.html', './jovan-19.html', './jovan-20.html',
  './jovan-21.html',
  './matej-1.html', './matej-2.html', './matej-3.html', './matej-4.html', './matej-5.html',
  './matej-6.html', './matej-7.html', './matej-8.html', './matej-9.html', './matej-10.html',
  './matej-11.html', './matej-12.html', './matej-13.html', './matej-14.html', './matej-15.html',
  './matej-16.html', './matej-17.html', './matej-18.html', './matej-19.html', './matej-20.html',
  './matej-21.html', './matej-22.html', './matej-23.html', './matej-24.html', './matej-25.html',
  './matej-26.html', './matej-27.html', './matej-28.html',
  './marko-1.html', './marko-2.html', './marko-3.html', './marko-4.html', './marko-5.html',
  './marko-6.html', './marko-7.html', './marko-8.html', './marko-9.html', './marko-10.html',
  './marko-11.html', './marko-12.html', './marko-13.html', './marko-14.html', './marko-15.html', 
  './marko-16.html',
  './luka-1.html', './luka-2.html', './luka-3.html', './luka-4.html', './luka-5.html',
  './luka-6.html', './luka-7.html', './luka-8.html', './luka-9.html', './luka-10.html',
  './luka-11.html', './luka-12.html', './luka-13.html', './luka-14.html', './luka-15.html',
  './luka-16.html', './luka-17.html', './luka-18.html', './luka-19.html', './luka-20.html',
  './luka-21.html', './luka-22.html', './luka-23.html', './luka-24.html',
  './o-molitvi-sv-jovan-krostantski.html',
  './jutarnje-molitve.html',
  './molitveno-pravilo-serafima-sarovskog.html',
  './bogorodice-djevo.html',
  './simbol-vere.html',
  './molitva-za-decu.html',
  './molitva-za-roditelje.html',
  './molitva-za-otvorenje-uma.html',
  './molitva-svetog-filareta.html',
  './velikoposna-molitva-svetog-jefrema-sirina.html',
  './molitva-pokajnika.html',
  './molitve-andjelu-cuvaru.html',
  './molitva-isusu-hristu.html',
  './molitve-svetim-arhangelima-za-svaki-dan-u-nedelji.html',
  './molitve-presvetoj-bogorodici-za-svaki-dan-u-nedelji.html',
  './molitva-za-spasenje-od-rasejanosti-uma.html',
  './molitva-bogorodici.html',
  './molitva-u-tuzi-dusevnoj.html',
  './molitva-za-upokojene.html',
  './molitva-za-upokojene-prestavljenih.html',
  './molitva-za-zastitu-od-necistih-sila.html',
  './pokajna-molitva.html',
  './molitva-za-oprostaj-greha.html',
  './molitva-presvetoj-bogorodici-brzopomocnici.html',
  './molitve-za-svetu-tajnu-braku.html',
  './molitva-presvetoj-bogorodici-u-nevolji-i-potistenosti.html',
  './molitve-svetom-vasiliju-ostroskom.html',
  './molitva-protiv-hulnih-pomisli.html',
  './zahvalna-molitva.html',
  './molitva-za-umnozenje-ljubavi.html',
  './molitva-za-one-koji-putuju.html',
  './molitva-svetom-naumu-ohridskom-cudotvorcu.html',
  './molitva-za-bolesnika.html',
  './molitva-pred-ispovest.html',
  './podsetnik-za-ispovest.html',
  './molitva-pred-sveto-pricesce.html',
  './molitva-posle-svetog-pricesca.html',
  './molitve-pre-i-posle-ucenja.html',
  './molitve-pre-spavanja.html',
  './molitva-pre-uzimanja-nafore-i-svete-vode.html',
  './hrabrost-za-molitvu.html',
  './ucenje-starca-vasilija-o-isusovoj-molitvi.html',
  './manifest.json',
  './svetitelji.json'
];

// 1. INSTALL (safe preload)
self.addEventListener('install', (event) => {
  self.skipWaiting();

  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      for (const url of OFFLINE_ASSETS) {
        try {
          await cache.add(url);
        } catch (e) {
          console.log('Preskačem:', url);
        }
      }
    })
  );
});

// 2. ACTIVATE (clean old caches)
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.map(k => (k !== CACHE_NAME ? caches.delete(k) : null))
      )
    )
  );

  self.clients.claim();
});

// 3. FETCH (STABLE iOS SAFE VERSION)
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  event.respondWith(
    (async () => {
      try {
        // 1. CACHE FIRST
        const cached = await caches.match(event.request);
        if (cached) return cached;

        // 2. NETWORK
        const response = await fetch(event.request);

        // 3. SAVE TO CACHE
        const cache = await caches.open(CACHE_NAME);
        cache.put(event.request, response.clone());

        return response;

      } catch (err) {

        // 4. NAVIGATION FALLBACK (ključ za Safari)
        if (event.request.mode === 'navigate') {
          const fallback = await caches.match('./index.html');
          return fallback || new Response('Offline', { status: 200 });
        }

        // 5. safe fallback (NE NULL!)
        return new Response('', { status: 200 });
      }
    })()
  );
});
